import { describe, it, expect, beforeEach } from "vitest";
import { auth } from "../src/auth";
import { setMailer, resetMailer } from "../src/email/mailer";

const headers = { "content-type": "application/json" };
const post = (path: string, body: unknown, cookie = "") =>
  auth.handler(
    new Request(`http://localhost:3000/api/auth${path}`, {
      method: "POST",
      headers: cookie ? { ...headers, cookie } : headers,
      body: JSON.stringify(body),
    }),
  );
const get = (path: string, cookie = "") =>
  auth.handler(
    new Request(`http://localhost:3000/api/auth${path}`, {
      headers: cookie ? { cookie } : {},
    }),
  );

describe("members & org lifecycle", () => {
  beforeEach(() => resetMailer());

  it("owner can add a member (via accept-new), change role, remove, and delete the org", async () => {
    // ── 1. capture the invitation id via the mailer spy ──────────────────────
    let invitationId = "";
    setMailer({
      sendInvite: async (e) => {
        invitationId = new URL(e.acceptUrl).searchParams.get("invitationId") ?? "";
      },
    });

    // ── 2. install + create org ───────────────────────────────────────────────
    const setup = await post("/install/setup", {
      name: "Admin",
      email: "admin@example.com",
      password: "supersecret123",
    });
    expect(setup.status).toBe(200);
    const ownerCookie = setup.headers.get("set-cookie") ?? "";

    // POST /organization/create — slug is auto-generated by the console plugin
    const org = await (
      await post("/organization/create", { name: "Acme", type: "company" }, ownerCookie)
    ).json();
    expect(org.id).toBeTruthy();

    // ── 3. invite + accept ────────────────────────────────────────────────────
    const inviteRes = await post(
      "/organization/invite-member",
      { email: "dev@example.com", role: "developer", organizationId: org.id },
      ownerCookie,
    );
    expect(inviteRes.status).toBe(200);
    expect(invitationId).toBeTruthy();

    // POST /invite/accept-new — custom endpoint; creates user + member in one tx
    const accepted = await (
      await post("/invite/accept-new", {
        invitationId,
        name: "Dev",
        password: "supersecret123",
      })
    ).json();
    expect(accepted.user?.id).toBeTruthy();
    const memberUserId: string = accepted.user.id;

    // ── 4. resolve the member-ROW id (not userId) via list-members ────────────
    // GET /organization/list-members?organizationId=... — body: { members, total }
    // Discovered from crud-members.mjs: updateMemberRole requires the member row
    // id (member.id), not the userId. list-members returns each member's {id, userId}.
    const listRes = await get(
      `/organization/list-members?organizationId=${org.id}`,
      ownerCookie,
    );
    expect(listRes.status).toBe(200);
    const { members } = (await listRes.json()) as { members: Array<{ id: string; userId: string; role: string }> };
    const devMemberRow = members.find((m) => m.userId === memberUserId);
    expect(devMemberRow).toBeTruthy();
    const devMemberId = devMemberRow!.id;

    // ── 5. promote to administrator ───────────────────────────────────────────
    // POST /organization/update-member-role — body: { role, memberId (row id), organizationId }
    // Discovered from crud-members.mjs updateMemberRoleBodySchema.
    const promote = await post(
      "/organization/update-member-role",
      { organizationId: org.id, memberId: devMemberId, role: "administrator" },
      ownerCookie,
    );
    expect([200, 201]).toContain(promote.status);

    // ── 6. remove the member ──────────────────────────────────────────────────
    // POST /organization/remove-member — body: { memberIdOrEmail, organizationId }
    // Discovered from crud-members.mjs removeMemberBodySchema. Accepts email string.
    const remove = await post(
      "/organization/remove-member",
      { organizationId: org.id, memberIdOrEmail: "dev@example.com" },
      ownerCookie,
    );
    expect(remove.status).toBe(200);

    // ── 7. delete the org ─────────────────────────────────────────────────────
    // POST /organization/delete — body: { organizationId }
    // Discovered from crud-org.mjs deleteOrganizationBodySchema.
    const del = await post("/organization/delete", { organizationId: org.id }, ownerCookie);
    expect(del.status).toBe(200);
  });
});
